services:
  influxdb:
    image: influxdb:2.7
    container_name: ${INFLUXDB_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - myInfluxVolume:/var/lib/influxdb2
      - influx-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: influx
      DOCKER_INFLUXDB_INIT_MODE: setup
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      DOCKER_INFLUXDB_INIT_USERNAME: ${USER_NAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${ORGANISATION}
      DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET_NAME}
    networks:
      - webapp-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: unless-stopped
    ports:
      - "2137:2137"
    env_file:
      - .env
    depends_on:
      - influxdb
    networks:
      - webapp-network

  frontend:
    build:
      context: ./frontend
    restart: unless-stopped
    ports:
      - "8888:2137"
    depends_on:
      - backend
    networks:
      - webapp-network

  test:
    build:
      context: .
      dockerfile: tests/Dockerfile
    restart: unless-stopped
    networks:
      - webapp-network

volumes:
  myInfluxVolume:
  influx-data:

networks:
  webapp-network:
