services:
  influxdb:
    image: influxdb:2.7
    restart: always
    container_name: ${INFLUXDB_CONTAINER_NAME}
    env_file:
      - .env
    volumes:
      - influx-data:/var/lib/influxdb2
    ports:
      - 8086:8086
    environment:
      INFLUXDB_DB: influx
      DOCKER_INFLUXDB_INIT_MODE: setup
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      DOCKER_INFLUXDB_INIT_USERNAME: ${USER_NAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${ORGANISATION}
      DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET_NAME}
    networks:
      - webapp-network

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    restart: always
    network_mode: "host"
    ipc: "host"
    privileged: true
    devices:
      - "/dev/ttyACM0:/dev/ttyACM0"
      - "/dev/ttyUSB0:/dev/ttyUSB0"
    env_file:
      - .env
    depends_on:
      - influxdb

  frontend:
    build:
      context: ./frontend
    restart: always
    ports:
      - "8888:2137"
    depends_on:
      - backend
    networks:
      - webapp-network

volumes:
  influx-data:

networks:
  webapp-network:
    name: gs_web_app_webapp-network
    driver: bridge