services:
  influxdb:
    image: influxdb:2.6.1
    container_name: influxdb
    env_file:
      - .env
    volumes:
      - myInfluxVolume:/var/lib/influxdb2
    environment:
      INFLUXDB_DB: influx
      DOCKER_INFLUXDB_INIT_MODE: setup
      INFLUXDB_HTTP_AUTH_ENABLED: "true"
      DOCKER_INFLUXDB_INIT_USERNAME: ${USER_NAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${PASSWORD}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${INFLUXDB_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${ORGANISATION}
      DOCKER_INFLUXDB_INIT_BUCKET: ${BUCKET_NAME}
    ports:
      - "8086:8086"
    restart: unless-stopped

  mavlink_bridge:
    build: .
    container_name: mavlink_bridge
    command: /app/venv/bin/python3 backend/mavlink_bridge.py
    env_file:
      - .env
    network_mode: "host"
    depends_on:
      - influxdb
    restart: no
    privileged: true

  backend_server:
    build: .
    container_name: backend_server
    command: /app/venv/bin/python3 backend/main.py
    env_file:
      - .env
    ports:
      - "2137:2137"
    environment:
      - INFLUXDB_HOST=influxdb
    depends_on:
      - influxdb
      - mavlink_bridge
    restart: unless-stopped

  test_publisher:
    build: .
    command: /app/venv/bin/python3 tests/ros/run.py
    env_file: [ .env ]
    profiles: [ "testing" ]
    depends_on: [ backend_server ]

volumes:
  myInfluxVolume: