apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    access: proxy
    url: http://${IP_ADDRESS}:${INFLUXDB_PORT}
    jsonData:
      version: Flux
      organization: ${ORGANISATION}
      defaultBucket: ${BUCKET_NAME}
      tlsSkipVerify: true
    secureJsonData:
      token: ${INFLUXDB_TOKEN}